# Generated by Django 3.0.6 on 2020-06-08 20:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20200606_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 20, 15, 23, 295238, tzinfo=utc)),
        ),
    ]
