# Generated by Django 3.0.6 on 2020-06-08 20:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20200609_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 20, 27, 10, 685618, tzinfo=utc)),
        ),
    ]
